language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36,check
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git shellcheck
install:
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
script:
  - tox
