# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-symlinks
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-executables-have-shebangs
-   repo: local
    hooks:
    -   id: go-fmt
        name: go fmt
        entry: ./scripts/go-fmt.sh
        files: '\.go$'
        language: script
    -   id: go-vet
        name: go vet
        entry: ./scripts/go-vet.sh
        files: '\.go$'
        language: script
    -   id: go-imports
        name: go imports
        entry: ./scripts/go-imports.sh
        files: '\.go$'
        language: script
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.21.0
    hooks:
    -   id: golangci-lint
        args: [--verbose, --timeout=3m]
        files: '\.go$'
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        files: '\.py$'
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.21.0
    hooks:
    -   id: terraform_fmt
        files: '\.tf$'
