# Infra deployment engine
platform: "openstack" # openstack, vmware, bare-metal, libvirt
workspace: "" # The top folder where skuba is stored
ssh_key_option: "id_shared" # "id_shared" or "id_rsa" for your local public key
username: ""  # Fill your username
nodeuser: "sles"  # Default node username
mirror: "ibs-mirror.prv.suse.net"

openstack:
  openrc: "" #os.getenv("OPENRC")

# node settings
lb:
  count: 1
  memory: 8192
  cpu: 4

master:
  count: 3
  memory: 4096
  cpu: 4

worker:
  count: 3
  memory: 4096
  cpu: 2

