#!/bin/bash

echo "Starting $0 script"

SDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
VENVDIR=${WORKSPACE:-~}/py3venv
export VENVDIR=${VENVDIR}

setup_python_env() {
    type python3 >/dev/null 2>&1 || sudo zypper install --no-confirm python3

    if [ ! -d $VENVDIR ]; then
        echo "Creating Python 3 virtualenv"
        python3 -m venv $VENVDIR
    fi
    source ${VENVDIR}/bin/activate
    UTILS_REQ_PATH="${SDIR}/utils/requirements.txt"
    TF_REQ_PATH="${SDIR}/platforms/requirements.txt"
    pip3 install -r "${UTILS_REQ_PATH}" -r "${TF_REQ_PATH}"&>/dev/null
    deactivate
}

setup_python_env
# use unbuffered output
stdbuf -i0 -o0 -e0  ${VENVDIR}/bin/python3 -u ${SDIR}/testrunner.py $@
