#!/bin/bash
set -eu
echo "Starting $0 script"

# Wrapper to testrunner.py to set up a virtualenv
# It can be run manually on developer workstations or under Jenkins

SDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# TODO: allow venv dir override
${SDIR}/../setup-python timeout-decorator

# Please track what components require each lib!

# wait-for-velum
${SDIR}/../setup-python requests

export VENVDIR=${WORKSPACE:-~}/py3venv

# use unbuffered output
stdbuf -i0 -o0 -e0  ${VENVDIR}/bin/python3 -u ${SDIR}/testrunner.py $@
